syntax = "proto3";
package zgc.wrappeda0gibase.v1;

import "cosmos_proto/cosmos.proto";
import "gogoproto/gogo.proto";
import "google/api/annotations.proto";
import "google/protobuf/any.proto";
import "google/protobuf/timestamp.proto";
import "zgc/wrappeda0gibase/v1/wrappeda0gibase.proto";

option go_package = "github.com/0glabs/0g-chain/x/wrapped-a0gi-base/types";
option (gogoproto.goproto_getters_all) = false;

// Query defines the gRPC querier service for the wrapped a0gi base module
service Query {
  rpc GetWA0GI(GetWA0GIRequest) returns (GetWA0GIResponse) {
    option (google.api.http).get = "/0g/wrapped-a0gi-base/get-wa0gi";
  }
  rpc MinterSupply(MinterSupplyRequest) returns (MinterSupplyResponse) {
    option (google.api.http).get = "/0g/wrapped-a0gi-base/minter-supply";
  }
}

message GetWA0GIRequest {}

message GetWA0GIResponse {
  bytes address = 1;
}

message MinterSupplyRequest {
  bytes address = 1;
}

message MinterSupplyResponse {
  Supply supply = 1;
}
