syntax = "proto3";
package zgc.wrappeda0gibase;

import "cosmos_proto/cosmos.proto";
import "gogoproto/gogo.proto";
import "google/api/annotations.proto";
import "google/protobuf/any.proto";
import "google/protobuf/timestamp.proto";

option go_package = "github.com/0glabs/0g-chain/x/wrapped-a0gi-base/types";
option (gogoproto.goproto_getters_all) = false;

// Query defines the gRPC querier service for the wrapped a0gi base module
service Query {
  rpc MinterSupply(MinterSupplyRequest) returns (MinterSupplyResponse) {
    option (google.api.http).get = "/0g/wrapped-a0gi-base/minter-supply";
  }
}

message MinterSupplyRequest {
  string address = 1;
}

message MinterSupplyResponse {
  string cap = 1;
  string supply = 2;
}
